export interface Course {
  id: string;
  title: string;
  slug: string;
  description: string;
  instructor: {
    name: string;
    avatar: string;
    title: string;
  };
  image: string;
  price: number;
  originalPrice: number;
  rating: number;
  reviewsCount: number;
  studentsCount: number;
  duration: string;
  lectures: number;
  level: "Beginner" | "Intermediate" | "Advanced" | "All Levels";
  category: string;
  subcategory: string;
  bestseller?: boolean;
  lastUpdated: string;
  language: string;
  whatYouWillLearn: string[];
  requirements: string[];
}

export interface Category {
  id: string;
  name: string;
  slug: string;
  icon: string;
  coursesCount: number;
  subcategories: string[];
}

export const categories: Category[] = [
  {
    id: "1",
    name: "AI & Data",
    slug: "development",
    icon: "🤖",
    coursesCount: 12,
    subcategories: ["AI Fundamentals", "Prompt Engineering", "Data Literacy", "Automation Basics", "AI Ethics"],
  },
  {
    id: "2",
    name: "Business",
    slug: "business",
    icon: "📊",
    coursesCount: 9,
    subcategories: ["Communication", "Management", "Sales", "Strategy", "Operations"],
  },
  {
    id: "3",
    name: "Design",
    slug: "design",
    icon: "🎨",
    coursesCount: 7,
    subcategories: ["UI Design", "Graphic Design", "UX Design", "Design Systems", "Branding"],
  },
  {
    id: "4",
    name: "Marketing",
    slug: "marketing",
    icon: "📈",
    coursesCount: 6,
    subcategories: ["Digital Marketing", "SEO", "Social Media", "Content Marketing", "Branding"],
  },
  {
    id: "5",
    name: "IT & Software",
    slug: "it-software",
    icon: "🖥️",
    coursesCount: 8,
    subcategories: ["IT Certifications", "Network Security", "Hardware", "Operating Systems", "DevOps"],
  },
  {
    id: "6",
    name: "Personal Development",
    slug: "personal-development",
    icon: "🧠",
    coursesCount: 5,
    subcategories: ["Leadership", "Productivity", "Personal Finance", "Career Development", "Happiness"],
  },
  {
    id: "7",
    name: "Photography",
    slug: "photography",
    icon: "📷",
    coursesCount: 4,
    subcategories: ["Digital Photography", "Portrait", "Landscape", "Video Production", "Commercial"],
  },
  {
    id: "8",
    name: "Music",
    slug: "music",
    icon: "🎵",
    coursesCount: 3,
    subcategories: ["Instruments", "Music Production", "Music Theory", "Vocals", "Music Software"],
  },
];

export const courses: Course[] = [
  {
    id: "1",
    title: "AI for Beginners",
    slug: "ai-for-beginners",
    description: "Start from zero and understand AI tools, key terms, and practical ways to use AI in everyday work.",
    instructor: {
      name: "Dr. Angela Yu",
      avatar: "https://images.pexels.com/photos/3796217/pexels-photo-3796217.jpeg?auto=compress&cs=tinysrgb&w=150&h=150&dpr=1",
      title: "Developer & Lead Instructor",
    },
    image: "https://images.pexels.com/photos/1181671/pexels-photo-1181671.jpeg?auto=compress&cs=tinysrgb&w=800",
    price: 12.99,
    originalPrice: 89.99,
    rating: 4.6,
    reviewsCount: 84,
    studentsCount: 420,
    duration: "8 hours",
    lectures: 52,
    level: "Beginner",
    category: "AI & Data",
    subcategory: "AI Fundamentals",
    bestseller: true,
    lastUpdated: "December 2024",
    language: "English",
    whatYouWillLearn: [
      "Build 16 web development projects for your portfolio",
      "Learn the latest technologies including JavaScript, React, Node and MongoDB",
      "Build fully-fledged websites and web apps for your startup or business",
      "Master frontend development with React",
      "Master backend development with Node",
    ],
    requirements: ["No programming experience needed", "A computer with access to the internet", "No paid software required"],
  },
  {
    id: "2",
    title: "AI for Corporate Institutions",
    slug: "ai-for-corporate-institutions",
    description: "Train teams to adopt AI responsibly, improve operations, and build repeatable workflows across departments.",
    instructor: {
      name: "Jose Portilla",
      avatar: "https://images.pexels.com/photos/2379004/pexels-photo-2379004.jpeg?auto=compress&cs=tinysrgb&w=150&h=150&dpr=1",
      title: "Head of Data Science, Pierian Training",
    },
    image: "https://images.pexels.com/photos/1181677/pexels-photo-1181677.jpeg?auto=compress&cs=tinysrgb&w=800",
    price: 14.99,
    originalPrice: 129.99,
    rating: 4.7,
    reviewsCount: 56,
    studentsCount: 260,
    duration: "10 hours",
    lectures: 68,
    level: "Intermediate",
    category: "AI & Data",
    subcategory: "Automation Basics",
    bestseller: true,
    lastUpdated: "November 2024",
    language: "English",
    whatYouWillLearn: [
      "Use Python for Data Science and Machine Learning",
      "Implement Machine Learning Algorithms",
      "Use NumPy for Numerical Data",
      "Use Pandas for Data Analysis",
      "Learn how to use Matplotlib for Python Plotting",
    ],
    requirements: ["Some programming experience", "Basic math knowledge"],
  },
  {
    id: "3",
    title: "Prompt Engineering Essentials",
    slug: "prompt-engineering-essentials",
    description: "Learn structured prompting techniques to get consistent, high-quality outputs from modern AI models.",
    instructor: {
      name: "Sarah Chen",
      avatar: "https://images.pexels.com/photos/3756679/pexels-photo-3756679.jpeg?auto=compress&cs=tinysrgb&w=150&h=150&dpr=1",
      title: "Senior UX Designer at Google",
    },
    image: "https://images.pexels.com/photos/196644/pexels-photo-196644.jpeg?auto=compress&cs=tinysrgb&w=800",
    price: 11.99,
    originalPrice: 79.99,
    rating: 4.8,
    reviewsCount: 73,
    studentsCount: 310,
    duration: "6 hours",
    lectures: 40,
    level: "Beginner",
    category: "AI & Data",
    subcategory: "Prompt Engineering",
    bestseller: true,
    lastUpdated: "January 2025",
    language: "English",
    whatYouWillLearn: [
      "Master Figma from the basics to advanced techniques",
      "Create stunning UI designs for web and mobile",
      "Understand UX principles and user research",
      "Build a professional design portfolio",
      "Land a job as a UI/UX designer",
    ],
    requirements: ["No design experience required", "A computer with Figma installed (free)"],
  },
  {
    id: "4",
    title: "AI Productivity for Teams",
    slug: "ai-productivity-for-teams",
    description: "Use AI assistants to speed up writing, reporting, planning, and internal communication in team settings.",
    instructor: {
      name: "Mark Thompson",
      avatar: "https://images.pexels.com/photos/2182970/pexels-photo-2182970.jpeg?auto=compress&cs=tinysrgb&w=150&h=150&dpr=1",
      title: "Digital Marketing Expert & Entrepreneur",
    },
    image: "https://images.pexels.com/photos/265087/pexels-photo-265087.jpeg?auto=compress&cs=tinysrgb&w=800",
    price: 13.99,
    originalPrice: 94.99,
    rating: 4.5,
    reviewsCount: 41,
    studentsCount: 180,
    duration: "5 hours",
    lectures: 34,
    level: "All Levels",
    category: "Business",
    subcategory: "Operations",
    lastUpdated: "October 2024",
    language: "English",
    whatYouWillLearn: [
      "Grow a business online from scratch",
      "Master SEO and rank #1 on Google",
      "Run profitable Facebook and Instagram Ads",
      "Build an email list and create marketing funnels",
      "Understand analytics and optimize your campaigns",
    ],
    requirements: ["No marketing experience needed", "Enthusiasm to learn"],
  },
  {
    id: "5",
    title: "Data Analysis with Excel and Power BI",
    slug: "data-analysis-excel-power-bi",
    description: "Analyze business data, build dashboards, and report insights clearly for decision-making.",
    instructor: {
      name: "Maximilian Schwarzmüller",
      avatar: "https://images.pexels.com/photos/1222271/pexels-photo-1222271.jpeg?auto=compress&cs=tinysrgb&w=150&h=150&dpr=1",
      title: "Professional Web Developer & Instructor",
    },
    image: "https://images.pexels.com/photos/11035471/pexels-photo-11035471.jpeg?auto=compress&cs=tinysrgb&w=800",
    price: 12.99,
    originalPrice: 99.99,
    rating: 4.6,
    reviewsCount: 63,
    studentsCount: 295,
    duration: "12 hours",
    lectures: 79,
    level: "All Levels",
    category: "AI & Data",
    subcategory: "Data Literacy",
    bestseller: true,
    lastUpdated: "December 2024",
    language: "English",
    whatYouWillLearn: [
      "Build powerful, fast, user-friendly and reactive web apps",
      "Apply for high-paid jobs or work as a freelancer",
      "Learn all about React Hooks and React Components",
      "Manage complex state efficiently with Redux",
      "Learn routing, authentication, and deployment",
    ],
    requirements: ["JavaScript + HTML + CSS fundamentals", "Basic understanding of ES6+ features"],
  },
  {
    id: "6",
    title: "Cybersecurity Basics for Professionals",
    slug: "cybersecurity-basics-for-professionals",
    description: "Understand modern cyber risks, safe practices, and essential security controls for workplaces.",
    instructor: {
      name: "Phil Ebiner",
      avatar: "https://images.pexels.com/photos/1239291/pexels-photo-1239291.jpeg?auto=compress&cs=tinysrgb&w=150&h=150&dpr=1",
      title: "Professional Photographer & Educator",
    },
    image: "https://images.pexels.com/photos/1092671/pexels-photo-1092671.jpeg?auto=compress&cs=tinysrgb&w=800",
    price: 10.99,
    originalPrice: 69.99,
    rating: 4.5,
    reviewsCount: 37,
    studentsCount: 155,
    duration: "7 hours",
    lectures: 44,
    level: "All Levels",
    category: "IT & Software",
    subcategory: "Network Security",
    lastUpdated: "September 2024",
    language: "English",
    whatYouWillLearn: [
      "Take amazing photos with any camera",
      "Understand camera settings and equipment",
      "Master photo composition techniques",
      "Edit photos professionally in Lightroom and Photoshop",
      "Start a photography business and sell your photos",
    ],
    requirements: ["A camera (any type)", "Passion for photography"],
  },
  {
    id: "7",
    title: "The Complete Financial Analyst Training & Investing Course",
    slug: "financial-analyst-training",
    description: "Succeed as a Financial Analyst by learning Excel, Accounting, Financial Statement Analysis, Business, Investing & more.",
    instructor: {
      name: "Chris Haroun",
      avatar: "https://images.pexels.com/photos/614810/pexels-photo-614810.jpeg?auto=compress&cs=tinysrgb&w=150&h=150&dpr=1",
      title: "Award Winning MBA Professor & Venture Capitalist",
    },
    image: "https://images.pexels.com/photos/6801648/pexels-photo-6801648.jpeg?auto=compress&cs=tinysrgb&w=800",
    price: 14.99,
    originalPrice: 119.99,
    rating: 4.5,
    reviewsCount: 34567,
    studentsCount: 189234,
    duration: "33 hours",
    lectures: 276,
    level: "All Levels",
    category: "Business",
    subcategory: "Entrepreneurship",
    lastUpdated: "November 2024",
    language: "English",
    whatYouWillLearn: [
      "Become a complete financial analyst",
      "Master Excel for financial analysis",
      "Analyze financial statements like a pro",
      "Understand investment strategies",
      "Build financial models from scratch",
    ],
    requirements: ["Basic computer skills", "Interest in finance"],
  },
  {
    id: "8",
    title: "AWS Certified Solutions Architect Associate 2024",
    slug: "aws-solutions-architect",
    description: "Pass the AWS Certified Solutions Architect Associate exam! Complete course with hands-on labs.",
    instructor: {
      name: "Stephane Maarek",
      avatar: "https://images.pexels.com/photos/2379005/pexels-photo-2379005.jpeg?auto=compress&cs=tinysrgb&w=150&h=150&dpr=1",
      title: "AWS Certified Solutions Architect & Developer",
    },
    image: "https://images.pexels.com/photos/1148820/pexels-photo-1148820.jpeg?auto=compress&cs=tinysrgb&w=800",
    price: 13.99,
    originalPrice: 109.99,
    rating: 4.7,
    reviewsCount: 156789,
    studentsCount: 567890,
    duration: "27 hours",
    lectures: 345,
    level: "Intermediate",
    category: "IT & Software",
    subcategory: "IT Certifications",
    bestseller: true,
    lastUpdated: "January 2025",
    language: "English",
    whatYouWillLearn: [
      "Pass the AWS Certified Solutions Architect Associate exam",
      "Understand AWS fundamentals and key services",
      "Design highly available and fault-tolerant systems",
      "Implement secure applications on AWS",
      "Optimize costs and performance on AWS",
    ],
    requirements: ["Basic IT knowledge", "No prior AWS experience needed"],
  },
  {
    id: "9",
    title: "Complete Music Production Course: Make Electronic Music",
    slug: "music-production-electronic",
    description: "Learn music production in Ableton Live & make electronic music: EDM, house, techno & more. No experience needed!",
    instructor: {
      name: "Ian Alexander",
      avatar: "https://images.pexels.com/photos/1681010/pexels-photo-1681010.jpeg?auto=compress&cs=tinysrgb&w=150&h=150&dpr=1",
      title: "Professional Music Producer & DJ",
    },
    image: "https://images.pexels.com/photos/164938/pexels-photo-164938.jpeg?auto=compress&cs=tinysrgb&w=800",
    price: 11.99,
    originalPrice: 84.99,
    rating: 4.6,
    reviewsCount: 23456,
    studentsCount: 145678,
    duration: "18 hours",
    lectures: 134,
    level: "Beginner",
    category: "Music",
    subcategory: "Music Production",
    lastUpdated: "October 2024",
    language: "English",
    whatYouWillLearn: [
      "Produce professional electronic music",
      "Master Ableton Live from scratch",
      "Create beats, melodies, and basslines",
      "Mix and master your tracks",
      "Release your music on Spotify and other platforms",
    ],
    requirements: ["Computer capable of running Ableton Live", "No music experience required"],
  },
  {
    id: "10",
    title: "Leadership: Practical Leadership Skills",
    slug: "practical-leadership-skills",
    description: "Master leadership skills and leadership techniques with this practical leadership training course.",
    instructor: {
      name: "Chris Croft",
      avatar: "https://images.pexels.com/photos/2406949/pexels-photo-2406949.jpeg?auto=compress&cs=tinysrgb&w=150&h=150&dpr=1",
      title: "Management Trainer & Leadership Coach",
    },
    image: "https://images.pexels.com/photos/3184360/pexels-photo-3184360.jpeg?auto=compress&cs=tinysrgb&w=800",
    price: 12.99,
    originalPrice: 74.99,
    rating: 4.6,
    reviewsCount: 45678,
    studentsCount: 234567,
    duration: "5 hours",
    lectures: 42,
    level: "All Levels",
    category: "Personal Development",
    subcategory: "Leadership",
    lastUpdated: "August 2024",
    language: "English",
    whatYouWillLearn: [
      "Be a great leader that people want to follow",
      "Motivate and inspire your team",
      "Make better decisions as a leader",
      "Handle difficult conversations and conflicts",
      "Build a high-performing team",
    ],
    requirements: ["None! Just a desire to become a better leader"],
  },
  {
    id: "11",
    title: "iOS & Swift - The Complete iOS App Development Bootcamp",
    slug: "ios-swift-development-bootcamp",
    description: "From beginner to iOS App Developer with just one course! Fully updated with all the latest iOS 17 features.",
    instructor: {
      name: "Dr. Angela Yu",
      avatar: "https://images.pexels.com/photos/3796217/pexels-photo-3796217.jpeg?auto=compress&cs=tinysrgb&w=150&h=150&dpr=1",
      title: "Developer & Lead Instructor",
    },
    image: "https://images.pexels.com/photos/699122/pexels-photo-699122.jpeg?auto=compress&cs=tinysrgb&w=800",
    price: 12.99,
    originalPrice: 89.99,
    rating: 4.8,
    reviewsCount: 87654,
    studentsCount: 345678,
    duration: "59 hours",
    lectures: 523,
    level: "All Levels",
    category: "Development",
    subcategory: "Mobile Development",
    bestseller: true,
    lastUpdated: "December 2024",
    language: "English",
    whatYouWillLearn: [
      "Build any iOS app you want",
      "Master Swift programming language",
      "Create apps with beautiful UI using SwiftUI",
      "Implement Core Data for data persistence",
      "Submit apps to the App Store",
    ],
    requirements: ["A Mac computer", "No programming experience needed"],
  },
  {
    id: "12",
    title: "Blender 3D Character Creation: Design & Model a Stylized Character",
    slug: "blender-3d-character-creation",
    description: "Learn to create stunning 3D characters in Blender. From concept to final render, master character modeling!",
    instructor: {
      name: "Grant Abbitt",
      avatar: "https://images.pexels.com/photos/2379003/pexels-photo-2379003.jpeg?auto=compress&cs=tinysrgb&w=150&h=150&dpr=1",
      title: "3D Artist & Blender Guru",
    },
    image: "https://images.pexels.com/photos/4348401/pexels-photo-4348401.jpeg?auto=compress&cs=tinysrgb&w=800",
    price: 10.99,
    originalPrice: 59.99,
    rating: 4.7,
    reviewsCount: 34567,
    studentsCount: 123456,
    duration: "16 hours",
    lectures: 112,
    level: "Intermediate",
    category: "Design",
    subcategory: "3D & Animation",
    lastUpdated: "November 2024",
    language: "English",
    whatYouWillLearn: [
      "Create stylized 3D characters from scratch",
      "Master Blender sculpting and modeling tools",
      "Learn topology and retopology techniques",
      "Create realistic textures and materials",
      "Rig and pose your characters",
    ],
    requirements: ["Blender installed (free)", "Basic Blender knowledge helpful but not required"],
  },
];

export const testimonials = [
  {
    id: "1",
    name: "Tafadzwa Moyo",
    role: "Junior Software Developer, Harare",
    avatar: "https://images.pexels.com/photos/1222271/pexels-photo-1222271.jpeg?auto=compress&cs=tinysrgb&w=150&h=150&dpr=1",
    content: "The lessons were practical and easy to follow even with load-shedding schedules. I built my first portfolio and secured a junior developer role in Harare.",
    rating: 5,
  },
  {
    id: "2",
    name: "Rumbidzai Chikore",
    role: "Freelance UI Designer, Bulawayo",
    avatar: "https://images.pexels.com/photos/3756679/pexels-photo-3756679.jpeg?auto=compress&cs=tinysrgb&w=150&h=150&dpr=1",
    content: "I loved that the projects reflected real business needs in Zimbabwe. The UI and branding modules helped me win consistent freelance design work.",
    rating: 5,
  },
  {
    id: "3",
    name: "Kudakwashe Sibanda",
    role: "Operations Officer, Gweru",
    avatar: "https://images.pexels.com/photos/2379004/pexels-photo-2379004.jpeg?auto=compress&cs=tinysrgb&w=150&h=150&dpr=1",
    content: "These courses gave me practical Excel and data skills I use daily at work. The local examples made everything easier to apply immediately.",
    rating: 5,
  },
];

export const stats = [
  { label: "Active students", value: "1,200+" },
  { label: "Courses", value: "24" },
  { label: "Programs", value: "6" },
  { label: "Enrollments", value: "3,800+" },
];

export const navLinks = [
  { label: "Categories", href: "/categories" },
  { label: "My Learning", href: "/my-learning" },
];
